--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/XPocketMC/DailyRewards
build-by-default: true
branches:
- main
projects:
  DailyRewards:
    libs:
  - src: jojoe77777/FormAPI/libFormAPI
    version: ^2.1.1
    path: ""
...
