name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  all-php-versions:
    name: PHP ${{ matrix.php }}
    strategy:
      fail-fast: false
      matrix:
        php: ["8.1", "8.2", "8.3"]

    uses: ./.github/workflows/main-php-matrix.yml
    secrets: inherit
    
steps:
- name: Composer Install
  run: sudo su && mv compose.json composer.json
  
